on:
  pull_request:
  push:

jobs:
  default:
    steps:
      - uses: actions/checkout@v2
      - uses: iffy/install-nim@v3
        with:
          version: 0.18.0
      - run: nim c -d:ssl -r package_scanner.nim
      - run: node ./validate_json.js
